#!/bin/bash
# Eliminem paperera
/usr/bin/find /srv/exports/Paperera/Paperera_Unitat_T/* -mtime +7 -exec rm -fr {} \; > /dev/null 2>&1

/usr/bin/find /srv/exports/Paperera/Paperera_Unitat_M/* -mtime +7 -exec rm -fr {} \; > /dev/null 2>&1

/usr/bin/find /srv/exports/Paperera/Paperera_Unitat_P/* -mtime +7 -exec rm -fr {} \; > /dev/null 2>&1

/usr/bin/find /srv/exports/Paperera/Paperera_Unitat_G/* -mtime +7 -exec rm -fr {} \; > /dev/null 2>&1

# Eliminem arxius infectats
/usr/bin/find /var/quarantine -mtime +7 -exec rm {} \; 2>&1
