---
- name: Servidor de centre
  hosts: servidor
  remote_user: anuser
  become: yes
  become_method: sudo

  roles:
    - unitats
    - nfs
    - smb
    - dlna
    - webmin
#    - nextcloud
#    - onlyoffice
#    - clam_antivirus
#    - jclic
