---
- name: Aplicant la configuració del paquet onlyoffice-documentserver 
  command: debconf-set-selections /usr/share/linkat/linkat-servidor/configurador/files/debconf.onlyoffice-documentserver

- name: Directori SSL Onlyoffice
  file:
        path: /etc/ssl/onlyoffice
        state: directory
        owner: root
        group: root
        mode: 0644

- name: Generant claus Onlyoffice
  command: openssl req -x509 -nodes -days 36500 -newkey rsa:2048 -keyout /etc/ssl/onlyoffice/onlyoffice.key -out /etc/ssl/onlyoffice/onlyoffice.crt -subj "/C=ES/ST=Catalunya/L=Barcelona/O=Generalitat de Catalunya/OU=Departament Ensenyament/CN=xtec.cat"

- name: Instal·lant els paquets del servidor LDAP
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
  - onlyoffice-documentserver 

- name: Copiant fitxers de configuració Onlyoffice 
  copy: src=files/onlyoffice-documentserver.conf dest=/etc/nginx/conf.d/onlyoffice-documentserver.conf

- file:
        path: /etc/nginx/conf.d/onlyoffice-documentserver.conf
        owner: root
        group: root
        mode: 0644

- name: Activant servei nginx 
  service: name=nginx state=started enabled=yes
  notify: restart nginx
